services:
  backend:
    container_name: backend
    image: stormwatch1979/backend-kpd:1.0.1
    env_file: .env
    ports:
      - "4000:3000"
    depends_on:
      - postgres
    restart: always
    networks:
      - internal

  frontend:
    container_name: frontend
    image: stormwatch1979/frontend-kpd:1.0.1
    env_file: .env
    ports:
      - "8081:80"
    restart: always
    networks:
      - external

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
  external:
