version: '3.9'
services:
  backend:
    container_name: kupipodariday-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stormwatch1979/kupipodariday-backend:16-alpine
    env_file:
      - .env
    ports:
      - 4000:3000
    networks:
      - internal-network

  frontend:
    container_name: kupipodariday-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: stormwatch1979/kupipodariday-frontend:16-alpine
    ports:
      - 8081:80
    networks:
      - internal-network

  database:
    container_name: kupipodariday-database
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:${PGDATA}
    networks:
      - internal-network

volumes:
  pgdata:

networks:
  internal-network:
